name: Unity Build

on:
  push:
    branches: [ "main" ]  # Trigger on pushes to main
  pull_request: {}         # Optional: Trigger on PRs

jobs:
  build:
    runs-on: windows-latest  # Or windows/macos

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true  # Required for Git LFS assets

      # Cache Unity Library to speed up builds
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('ProjectSettings/ProjectVersion.txt') }}
          
      # Build project using the unified builder action
      - name: Build Project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2022.3.20f1   # Match your project's Unity version
          targetPlatform: StandaloneWindows64_IL2CPP  # Options: WebGL, iOS, Android, etc.
          buildName: MyGame
          buildsPath: Builds

      # Upload build artifacts using the updated v4 action
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: Builds
