name: Unity Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code (updated to v4)
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache Unity Library (updated to v4)
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('ProjectSettings/ProjectVersion.txt') }}
          
      # Fix: Use correct setup action name and version
      - name: Setup Unity
        uses: game-ci/setup-unity@v1  # <-- Updated action name
        with:
          unityVersion: 2021.3.23f1

      # Fix: Use latest activation action (v3)
      - name: Activate License
        uses: game-ci/unity-request-activation-file@v3
        with:
          unityVersion: ${{ steps.setup.outputs.unityVersion }}
          
      # Fix: Use latest builder (v3)
      - name: Build Project
        uses: game-ci/unity-builder@v3  # <-- Updated to v3
        with:
          targetPlatform: StandaloneWindows64
          buildName: MyGame
          buildsPath: Builds

      # Fix: Update upload-artifact to v4
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4  # <-- Updated to v4
        with:
          name: Build
          path: Builds