name: Unity Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache Unity Library
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('ProjectSettings/ProjectVersion.txt') }}

      # Setup Unity (updated action name)
      - name: Setup Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2023.3.23f1  # Use camelCase, not "unity-version"

      # Build project (updated action name)
      - name: Build Project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64
          buildName: MyGame
          buildsPath: Builds
          unityUsername: ${{ secrets.UNITY_EMAIL }}
          unityPassword: ${{ secrets.UNITY_PASSWORD }}

      # Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path:
