name: Update Unity project semantic versioning

on: [push, workflow_dispatch]

jobs:
    create:
        name: Update semver
        runs-on: ubuntu-latest

        steps:
            # You must ALWAYS checkout your repo so that actions in the workflow can use it.
            - name: Checkout
              uses: actions/checkout@v4

            - name: Find ProjectSettings.asset & increment its bundleVersion number
              uses: AlexStormwood/UnityAutomatedSemver@v2.0.0 # Change v1.1.1 to whatever tag is newer in the AlexStormwood/UnityAutomatedSemver repository.
              id: semver-update
              with:
                  updateMode: "patch" # Change this string to any suitable string mentioned in the Inputs section of this action's readme to suit your needs.
                  projectSettingsPath: "ProjectSettings/ProjectSettings.asset" # optional: specify the exact location of the ProjectSettings file, otherwise action will attempt to automatically find it.

            # Validate that the number has been incremented correctly.
            - name: Get the new semver value
              run: echo "The new semver number for this Unity project is ${{ steps.semver-update.outputs.semver-string }}"

            - name: Get the full semver data from the action
              run: echo "Full semver data is ${{ steps.semver-update.outputs.semver-full-data }}"

            # Commit & push the updated semver number back into the repo. Yes, you have to fetch & pull in your local workstation after this step is done.
            - name: Push changed files back to repo
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "Updated semver via automated action."
                  commit_options: "--no-verify --signoff"

                  