name: Update Unity Version on Merge

on:
  pull_request:
    types: [push]
    branches:
      - development

jobs:
  bump-version:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Important: disable credential persistence so your custom token settings are used
          persist-credentials: false

      - name: Bump Version using Unity Automated Semver
        uses: AlexStormwood/UnityAutomatedSemver@v2.0.0
        id: semver
        with:
          updateMode: "patch"  # Or "major" or "minor" as needed
          projectSettingsPath: "ProjectSettings/ProjectSettings.asset"

      - name: Verify New Version
  run: |
    echo "New version: ${{ steps.semver.outputs['semver-string'] }}"



      - name: Commit and Push Version Change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update version to ${{ steps.semver.outputs.semver-string }} [skip ci]"
          commit_options: "--no-verify --signoff"
