name: Update Version and Build

on: [push, workflow_dispatch]

jobs:
  update_semver:
    name: Update Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Update Unity SemVer
        uses: AlexStormwood/UnityAutomatedSemver@v2.0.0
        id: semver-update
        with:
          updateMode: "patch"
          projectSettingsPath: "ProjectSettings/ProjectSettings.asset"

      - name: Commit and Push Version Change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated semver to ${{ steps.semver-update.outputs.semver-string }} [skip ci]"
          file_pattern: ProjectSettings/ProjectSettings.asset
          commit_options: "--no-verify --signoff"

  build:
    name: Build Project
    needs: update_semver  # Wait for the version update job
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64
          - iOS
          - Android
          - WebGL
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}